name: Wake Up Private HF Space
on:
  schedule:
    - cron: '*/30 * * * *' 
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Authenticated Ping
        run: |
          curl -I -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" https://nirjhar8-testing.hf.space
